### ISSUE TITLE
Support for 1.7

### ISSUE THREAD

**Issue by petekaras** [svenkubiak/ninja-authentication#2]
Hi,
What are the dependencies of this plugin on Java 1.8.
Would it be possible to run on 1.7 ?
Thanks for your help,
Peter

**Comment by svenkubiak** [comment]
Hey Peter,

afaik, there is not hard dependency on java 1.8 functions (yet). The main reason for droping support of 1.7 is that 1.7 will go eol in april 2015. So, why not start migrating ;-)

Cheers,
Sven
